image: alpine:latest  # ใช้ Alpine Linux

before_script:
  - apk add --no-cache git  # ติดตั้ง Git
  - git --version           # เช็คว่า Git ใช้งานได้

stages:
  - sync

sync_repo:
  stage: sync
  script:
    - git config --global user.name "GitLab CI"
    - git config --global user.email "gitlab-ci@localhost"

    # ลบ remote origin (ถ้ามีอยู่แล้ว) แล้วเพิ่มใหม่ให้เป็น GitHub
    - git remote remove origin || true
    - git remote add origin https://oauth2:${GITHUB_TOKEN}@github.com/41837/ubuntu24.04.1_frappe_pet_store.git

    # ดึงโค้ดจาก GitHub และ push ไป GitLab
    - git fetch origin main
    - git checkout -B develop origin/main  # Sync จาก GitHub main → GitLab develop
    - git push gitlab develop  # push ไปที่ GitLab
  only:
    - develop
