# image: alpine:latest

# before_script:
#   - apk add --no-cache git
#   - git --version
#   - git config --global http.sslVerify false

# stages:
#   - sync

# sync_from_github:
#   stage: sync
#   script:
#     - git remote remove github || true
#     - git remote -v
#     - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/41837/ubuntu24.04.1_frappe_pet_store.git || true
#     - git remote -v
#     - git branch -r
#     - git fetch --all
#     - git fetch github
#     - git merge github/main --no-edit
#     - git push origin main
#   only:
#     - main

image: alpine:latest

before_script:
  - apk add --no-cache git
  - git --version
  - git config --global http.sslVerify false
  - git config --global user.name "GitLab CI"
  - git config --global user.email "gitlab-ci@localhost"

stages:
  - sync

sync_from_github:
  stage: sync
  script:
    # ตั้งค่า remote สำหรับ GitHub
    - git remote remove github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/41837/ubuntu24.04.1_frappe_pet_store.git || true
    - git remote -v
    - git branch -r

    # ดึงโค้ดจาก GitHub
    - git fetch github
    - git checkout main || git checkout -b main github/main
    - git status

    # Merge main → develop แล้ว push ไปที่ GitLab
    - git merge github/main --no-edit
    - git push origin develop
  only:
    - main
