image: alpine:latest

before_script:
  - apk add --no-cache git
  - apk add --no-cache openssh-client
  - git config --global user.name "tin.t"
  - git config --global user.email "tin.t@srisawadpower.com"

stages:
  - sync

sync_from_github:
  stage: sync
  script:
    # Connect GitHub
    - git remote remove github || true
    - git remote add github git@github.com:41837/ubuntu24.04.1_frappe_pet_store.git

    # GitHub step
    - git remote -v

    # Merge between repository
    - git fetch github main
    - git status
    - git diff github/main origin/main

  only:
    - main