image: ubuntu:latest

before_script:
  - apt-get update -y
  - apt-get install -y openssh-client libssl-dev
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMuoEpiwmPhS9qXs5N/rZsPgMVJmpcM/+07RkbrNQLlb developer.swp@frappe.local" > ~/.ssh/id_ed25519
  - chmod 600 ~/.ssh/id_ed25519
  - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  - chmod 600 ~/.ssh/config
  - ssh-keyscan -H 10.1.112.134 >> ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/known_hosts
  - export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no"

  - apt install git -y
  - git --version

stages:
  - sync

sync_from_github:
  stage: sync
  script:
    - ls -la
    - git remote -v
    - echo "Hostname of the machine:"
    - hostname
    - echo "Uptime of the machine:"
    - uptime
    - git fetch github
    - echo "testing..."

  only:
    - main
